/* Built-in banks. Analytical verbs are kept separate from text-study concepts. */
(function(){
const banks={
general:['journey','forest','courage','memory','storm','friendship','shadow','discovery','challenge','change','freedom','danger','hope','silence','choice','power','home','secret','truth','conflict'],
grammar:['noun','verb','adjective','adverb','pronoun','preposition','conjunction','clause','phrase','object','subject','tense','modality','syntax','punctuation','nominalisation'],
persuasive:['modality','rhetorical question','inclusive language','emotive language','repetition','statistics','expert opinion','anecdote','imperative','appeal','contention','audience','purpose','tone'],
literary:['metaphor','simile','personification','symbolism','imagery','juxtaposition','foreshadowing','allusion','irony','motif','characterisation','setting','narrative voice','diction','contrast','syntax'],
analytical:['represents','constructs','positions','suggests','reveals','reinforces','challenges','foregrounds','contrasts','symbolises','emphasises','conveys','complicates','invites','assumes','supports','endorses','highlights','conceals','exposes','discloses','questions','undermines','implies','asserts'],
creative:['mystery','tension','setting','voice','imagery','dialogue','conflict','character','symbol','motif','flashback','sensory detail','pace','viewpoint','tone'],
textstudy:['character','setting','event','relationship','quotation','concept','representation','perspective','theme','conflict','turning point','symbol','motif','genre convention','assumption','value','belief']
};
const categoryPools={general:['animals','foods','places','objects','emotions','actions'],grammar:['nouns','verbs','adjectives','adverbs','conjunctions','sentence types'],persuasive:['persuasive techniques','appeals','high-modality words','emotive words','analytical verbs'],literary:['language features','literary devices','character traits','mood words','Gothic conventions'],analytical:['analytical verbs'],creative:['setting words','sensory verbs','character traits','mood words','dialogue verbs'],textstudy:['characters','settings','events','relationships','concepts','quotations']};
const plainSentences=['The character walked into the room.','The wind moved through the trees.','She opened the letter.','He looked across the field.','The door closed behind them.','The crowd became quiet.'];
const storyConstraints={easy:['Build any coherent classroom-safe story.'],medium:['Mystery genre','Past tense','Set in a school','Use at least one adverb','Set in space','Include a storm'],hard:['Create a tense tone','Use first-person perspective','Build towards a twist','Include a recurring symbol','Create a hopeful tone','Use deliberately short sentences']};
const clues={
'noun':'a word that names a person, place, thing or idea',
'verb':'a word that expresses an action, process or state',
'adjective':'a word that describes or modifies a noun',
'adverb':'a word that modifies a verb, adjective or another adverb',
'pronoun':'a word used in place of a noun or noun group',
'preposition':'a word that shows a relationship such as place, time or direction',
'conjunction':'a word that joins words, phrases or clauses',
'clause':'a group of words built around a verb that forms part or all of a sentence',
'phrase':'a group of words that works as a unit but does not necessarily contain a complete clause',
'subject':'the person, thing or idea that a clause is about',
'tense':'the grammatical system used to locate actions or states in time',
'modality':'language that expresses degrees of certainty, obligation or possibility',
'syntax':'the arrangement of words and clauses within sentences',
'punctuation':'marks used to organise written language and shape meaning',
'nominalisation':'turning a verb, adjective or other form into a noun or noun group',
'rhetorical question':'a question asked for effect rather than to obtain an answer',
'inclusive language':'language that deliberately includes the audience in a group or shared position',
'emotive language':'word choices designed to provoke an emotional response',
'repetition':'deliberate reuse of a word, phrase, sound or idea for emphasis or pattern',
'statistics':'numerical evidence used to support a claim',
'expert opinion':'evidence drawn from a person presented as knowledgeable or authoritative',
'anecdote':'a brief personal or illustrative story used to support a point',
'imperative':'a command form that directs someone to act or think in a particular way',
'contention':'the central position or argument a text advances',
'audience':'the people a text is designed to address',
'purpose':'what a text is trying to achieve',
'metaphor':'a comparison that describes one thing as another without using like or as',
'simile':'a comparison that commonly uses like or as',
'personification':'giving human qualities or actions to something non-human',
'symbolism':'the use of an object, image, place or action to carry additional meaning',
'imagery':'descriptive language that creates sensory or vivid mental impressions',
'juxtaposition':'placing elements close together so their similarities or differences become significant',
'foreshadowing':'an early hint or suggestion of something that will occur later',
'allusion':'an indirect reference to another text, person, event, myth or cultural idea',
'irony':'a contrast between expectation, appearance or stated meaning and what is actually meant or occurs',
'motif':'a recurring image, idea, object or pattern that contributes to meaning',
'characterisation':'the methods used to construct and develop a character',
'setting':'the time, place and social environment in which events occur',
'narrative voice':'the voice or position through which a story is told',
'diction':'a writer\u2019s deliberate choice of words',
'contrast':'a deliberate emphasis on differences between two or more things',
'perspective':'a position or way of viewing people, ideas, events or the world',
'representation':'the way a text constructs or presents a concept, identity, time, place or experience',
'assumption':'an idea treated as true or normal without necessarily being stated or proved',
'value':'a principle or quality regarded as important or desirable',
'belief':'an idea accepted as true or held to be important',
'tension':'a sense of pressure, uncertainty or conflict that keeps an audience anticipating what may happen',
'suspense':'deliberate uncertainty or anticipation about what will happen next',
'protagonist':'the central character whose goals or experiences drive much of the story',
'antagonist':'a person, force or obstacle that opposes the protagonist',
'relationship':'the connection or dynamic between people, characters, groups or ideas',
'conflict':'a struggle between competing goals, values, people or forces',
'tone':'the attitude or feeling conveyed through language and stylistic choices',
'theme':'a recurring or developed idea explored through a text',
'concept':'an abstract idea that can be represented and explored in different ways',
'quotation':'the exact words taken from a text as evidence',
'ordinary world':'the hero\u2019s familiar starting situation before the central journey begins',
'call to adventure':'the event, invitation or disruption that draws the hero towards the journey',
'refusal':'the stage where the hero resists, fears or avoids the call',
'mentor':'a guide who gives the hero advice, knowledge, training or support',
'threshold':'a boundary between the familiar world and a new or challenging space',
'guardian':'a figure or obstacle that tests whether the hero is ready to move forward',
'ally':'a person who supports the hero during the journey',
'enemy':'a person or force that works against the hero\u2019s goals',
'trickster':'a disruptive or comic figure who challenges expectations and can provoke change',
'crossing the threshold':'the point where the hero commits to leaving the familiar world and entering the journey',
'ordeal':'a major crisis or test in which the hero faces severe danger, loss or fear',
'reward':'what the hero gains after surviving or overcoming a major challenge',
'road back':'the stage where the hero begins the return journey and faces the consequences of what has happened',
'resurrection':'a final major test that demonstrates the hero\u2019s transformation',
'return':'the hero\u2019s movement back towards the ordinary world after the central journey',
'elixir':'the knowledge, gift, insight or benefit the hero brings back from the journey',
 'transformation':'a meaningful change in the hero\u2019s identity, understanding, values or behaviour',
'quest':'a purposeful journey towards a difficult goal',
'sacrifice':'giving up something valued for a larger purpose or another person',
'courage':'the willingness to act despite fear or danger',
'identity':'a sense of who a person is and how that self is understood or constructed',
'belonging':'a sense of connection, acceptance or membership within a group or place',
 'temptation':'an attraction towards a choice that may distract from a goal or challenge values',
'growth':'development in understanding, skill, character or maturity',
'failure':'an unsuccessful attempt or outcome that can create consequences or learning',
'perseverance':'continuing to work towards a goal despite difficulty or setbacks',
'homecoming':'a return home that may reveal how the traveller or home has changed',
'outsider':'a person positioned as separate from, excluded by or unfamiliar to a group',
'guide':'a person, voice or source that helps someone navigate a challenge or journey',
'adversity':'difficult conditions, misfortune or obstacles that must be faced',
'victory':'a successful outcome after conflict, struggle or competition',
'change':'a shift from one state, condition, belief or situation to another',
'represents':'presents or depicts an idea, person, group or experience in a particular way',
'constructs':'builds or shapes a particular meaning, identity or version of reality',
'positions':'encourages an audience to adopt a particular response or viewpoint',
'suggests':'puts forward an idea without necessarily stating it directly or conclusively',
'reveals':'makes previously hidden information or meaning apparent',
'reinforces':'strengthens an existing idea, attitude or belief',
'challenges':'questions or contests an idea, assumption or accepted position',
'foregrounds':'places something in a prominent position for the audience to notice',
'contrasts':'draws attention to differences between things',
'symbolises':'stands for or conveys an additional idea beyond its literal identity',
'emphasises':'gives particular importance or attention to something',
'conveys':'communicates an idea, impression or feeling',
'complicates':'makes an idea less simple by introducing additional factors or tensions',
'invites':'encourages an audience to consider or adopt a response',
'assumes':'treats an idea as true or given without necessarily establishing it',
'supports':'provides backing for an idea, position or interpretation',
'endorses':'expresses approval of or agreement with an idea or position',
'highlights':'makes something especially noticeable or important',
'conceals':'hides information or prevents it from being readily seen',
'exposes':'brings something hidden or concealed to attention',
'discloses':'makes previously unknown information known',
'questions':'expresses doubt about an idea or examines whether it should be accepted',
'undermines':'weakens the authority, credibility or force of something',
'implies':'communicates an idea indirectly rather than stating it explicitly',
'asserts':'states a position confidently as true'
};
window.GAME_DATA={banks,clues,categoryPools,plainSentences,storyConstraints};
})();
