// Authored clues for the remaining built-in entries.
Object.assign(window.GAME_DATA.clues,{
  "journey": "travel from one place or stage of experience to another",
  "forest": "a large area covered mainly by trees",
  "memory": "the ability to retain and recall information or experiences",
  "storm": "a period of violent weather, often with strong wind and rain",
  "friendship": "a close connection between people based on affection and trust",
  "shadow": "a dark area formed where something blocks light",
  "discovery": "the act or result of finding something not previously known",
  "challenge": "a difficult task or situation that tests ability or determination",
  "freedom": "the ability to act or choose without undue restriction",
  "danger": "the possibility of harm, injury or loss",
  "hope": "a feeling of expectation or desire for a positive outcome",
  "silence": "the absence of sound or the act of not speaking",
  "choice": "a decision between available possibilities",
  "power": "the capacity to act or influence people, events or conditions",
  "home": "a place where someone lives or feels a sense of belonging",
  "secret": "information intentionally kept from others",
  "truth": "what is consistent with fact or reality",
  "object": "a clause element that typically receives or is affected by the action of a verb",
  "appeal": "a persuasive approach that draws on values, emotions or reasoning",
  "mystery": "a genre centred on an unanswered question or event to be explained",
  "voice": "the distinctive expression or personality conveyed by a writer or narrator",
  "dialogue": "spoken exchanges between characters represented in a text",
  "character": "a person or other figure represented in a narrative",
  "symbol": "an element that stands for an idea beyond its literal identity",
  "flashback": "a shift in a narrative to an event earlier than the current action",
  "sensory detail": "description that evokes sight, sound, smell, taste or touch",
  "pace": "the rate at which events or information unfold in a narrative",
  "viewpoint": "the position from which events or ideas are presented",
  "event": "an occurrence or action that takes place within a narrative",
  "turning point": "a moment that significantly changes the direction of a narrative",
  "genre convention": "a familiar feature associated with a particular type of text"
});
